version: '3.8'
services:
  buman-backend-db:
    image: postgres:latest
    container_name: buman-backend-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  buman-backend:
    image: buman-backend:latest
    container_name: buman-backend
    restart: always
    ports:
      - '1480:1480'
    env_file:
      - .env
volumes:
  pg_data:
    name: buman-backend-db
